version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-producer
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: producer_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - producer-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-shared
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # RabbitMQ AMQP port
      - "15672:15672"  # RabbitMQ Management UI port
    networks:
      - producer-network
      - shared-rabbitmq-network  # Shared network so Consumer can access it
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 20s
      retries: 10

  producer-app:
    build: .
    container_name: student-producer
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/producer_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - producer-network
      - shared-rabbitmq-network
    restart: on-failure

volumes:
  mysql-data:

networks:
  producer-network:
    driver: bridge
  shared-rabbitmq-network:
    name: rabbitmq-network
    driver: bridge
